backend:
  name: github
  branch: master
  repo: gilbertlucas46/gilbert

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
  - name: 'services'
    label: 'Services'
    folder: 'src/services'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Service', name: 'title', widget: 'string' }
      - { label: "Service Image", name: "thumbnail", widget: "image"}
      - { label: 'Categories', name: 'categories', widget: 'string', required: true }
      - { label: "Type", name: "type", widget: "hidden", default: true}
  - name: 'myworks'
    label: 'My Works'
    folder: 'src/myworks'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Project Name', name: 'title', widget: 'string' }
      - { label: "Image", name: "thumbnail", widget: "image"}
      - { label: 'Categories', name: 'categories', widget: 'string', required: true }
      - { label: 'Project Nature', name: 'nature', widget: 'string' }
      - { label: 'info', name: 'body', widget: 'markdown' }
      - { label: "Type", name: "type", widget: "hidden", default: true}
  - name: 'blog'
    label: 'Blog'
    folder: 'src/posts'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumbnail", widget: "image"}
      - { label: "Category", name: "category", widget: "select", options: ["development", "design", "lifestyle"]}
      - { label: "Type", name: "type", widget: "select", default: "blog", options: ["blog", "page"]}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "metadata"
    label: "Metadata & Navigation"
    description: "Pages Metadatas"
    folder: "src/metadata"
    create: true
    fields:
      - {
          label: MetaData's,
          name: metadata,
          required: true,
          widget: list,
          fields:
            [
              { label: "Meta Title", name: "metatitle", widget: "string" },
              { label: "Title Template", name: "titleTemplate", widget: "hidden", default: "%s · Gilbert Lucas" },
              { label: "About Description", name: metadesc, widget: 'markdown' },
              { label: "Author", name: "author", widget: "hidden", default: "Gilbert lucas" },
              { label: "url", name: "url", widget: "hidden", default: "https://gilbert.codes" },
              { label: "siteUrl", name: "siteUrl", widget: "hidden", default: "https://gilbert.codes" },
              {
                label: Image,
                name: image,
                required: false,
                hint: "Image for the page",
                widget: image,
              },
              { label: "Owner", name: "owner", widget: "hidden", default: "Gilbertlucas" },
              { label: "Page name", name: "pagetitle", widget: "string" },
              { label: "twitterUsername", name: "url", widget: "hidden", default: "@gilbertlucas14" },
              { label: "facebookAppID", name: "url", widget: "hidden", default: " " }
            ]
          }
      - {
          label: Menu Links,
          name: menuLinks,
          required: true,
          widget: list,
          fields:
            [
              { label: "Page Name", name: "name", widget: "string" },
              { label: "Link to", name: link, widget: 'string' }
            ]
          }
      - {
          label: Social Channels,
          name: socialChannels,
          required: true,
          widget: list,
          fields:
            [
              { label: "Social Name", name: "name", widget: "string" },
              { label: "Link to", name: link, widget: 'string' }
            ]
          }


